from manim import *



class HorizonDetector(MovingCameraScene):
    
    def construct(self):
        # Creating the vertices of the triangle
        point_a = [-2, -2, -2]  # The origin
        point_b = [1, -2, -2]  # Three units along the x-axis
        point_c = [-2, 2, -2]  # Four units along the y-axis
        
        # Creating the triangle
        triangle = Polygon(point_a, point_b, point_c, color=BLUE)
        triangle.set_fill(GRAY, opacity=0.7)
        triangle.set_stroke(color=WHITE, width=5)
        # Showing the triangle
        self.play(Create(triangle))
        self.wait(2)
        lineb= Line(point_a,point_b)
        b=Brace(lineb)
        bText=b.get_text("b").set_color(GREEN)
        linea=Line(point_a,point_c)
        a=Brace(linea,direction=linea.copy().rotate(PI/2).get_unit_vector())
        aText=a.get_text("a").set_color(BLUE)
        linec=Line(point_c,point_b)
        c=Brace(linec,direction=linec.copy().rotate(PI/2).get_unit_vector())
        cText=c.get_text("c").set_color(RED)
        v=VGroup(b,bText,a,aText,c,cText)
        
        self.play(Create(v))
        
        self.wait(2)
        
        self.play(self.camera.frame.animate.set(width=20).move_to([2,2,2]))
        self.play(FadeOut(v))
        triangle1=triangle.copy()
        triangle2=triangle.copy()
        triangle3=triangle.copy()
        triangle4=triangle.copy()
        
        self.add(triangle1,triangle2,triangle3,triangle4)
        triangle.set_opacity(0)
        t2v=triangle2.animate.move_to(triangle.get_center()+[3.5,-0.5,0]).rotate(PI/2)
        t3v=triangle3.animate.move_to(triangle.get_center()+[0.5,3.5,0]).rotate(-PI/2)
        t4v=triangle4.animate.move_to(triangle.get_center()+[4,3,0]).rotate(PI)
        triangles=AnimationGroup(t2v,t3v,t4v)
        self.play(triangles)
        self.wait(2.0)
        horizonAll=Square()
        horizonAll.set_fill(opacity=0)  # 塗りつぶしなし
        horizonAll.set_stroke(color=RED, width=4)  # 枠の色を赤、幅を設定
        horizonAll.move_to([1.5,1.5,1.5])
        horizonAll.scale(3.5)
        outline = SurroundingRectangle(horizonAll, color=YELLOW, buff=0.05)
        self.play(Create(outline))
        self.wait(2.0)
        t3vText=Text("c",color=RED)
        t4vText=Text("c",color=RED)
        t3vText.move_to([3,3,0])
        t4vText.move_to([0.5,3,0])
        self.play(Write(t3vText),Write(t4vText))
        self.wait(2.0)
        t3v_move=t3vText.animate.move_to([1.5,1.25,1])
        t4v_move=t4vText.animate.move_to([1.5,1.25,1])
        cees=AnimationGroup(t3v_move,t4v_move)
        self.play(cees)
        ccText=MathTex("c^{2}",color=RED)
        ccText.move_to([1.5,1.5,1])
        ccText.scale(2.0)
        self.play(Write(ccText),Unwrite(t3vText),Unwrite(t4vText))
        self.play(self.camera.frame.animate.move_to([2,-1,2]))
        self.play(ccText.animate.move_to([4,-3,3]))
        self.wait(2.0)
        self.play(self.camera.frame.animate.move_to([2,2,2]))
        self.wait(3.0)
        self.play(triangle2.animate.move_to(triangle.get_center()+[0.5,3.5,0]))
        tr4_move=triangle4.animate.move_to(triangle.get_center()+[4,0,0])
        tr1_move=triangle1.animate.move_to(triangle.get_center()+[4,0,0])
        tr14_move=AnimationGroup(tr1_move,tr4_move)
        self.play(tr14_move)
        self.wait(2.0)
        moved_t1Texta=Text("a",color=BLUE)
        moved_t2Texta=Text("a",color=BLUE)
        moved_t2Textb=Text("b",color=GREEN)
        moved_t4Textb=Text("b",color=GREEN)
        moved_t1Texta.move_to([0,1.5,-1])
        moved_t2Texta.move_to([1.75,-0.25,-1])
        moved_t2Textb.move_to([3.5,2.5,-1])
        moved_t4Textb.move_to([2.4,3.5,-1])
        moved_tTexts=VGroup(moved_t1Texta,moved_t2Texta,moved_t2Textb,moved_t4Textb)
        self.play(Create(moved_tTexts))
        self.wait(4.0)
        move_t1Texta=moved_t1Texta.animate.move_to([0,-0.25,-1])
        move_t2Texta=moved_t2Texta.animate.move_to([0,-0.25,-1])
        move_t2Textb=moved_t2Textb.animate.move_to([3.5,3.5,-1])
        move_t4Textb=moved_t4Textb.animate.move_to([3.5,3.5,-1])
        move_t124Texts=AnimationGroup(move_t1Texta,move_t2Texta,move_t2Textb,move_t4Textb)
        Remove_t124Texts=Unwrite(moved_tTexts)
        self.play(move_t124Texts)
        aaText=MathTex("a^{2}",color=BLUE).scale(2.0)
        bbText=MathTex("b^{2}",color=GREEN).scale(2.0)
        bbText.move_to([3.5,3.5,-1])
        ab2Texts=VGroup(aaText,bbText)
        self.play(Remove_t124Texts)
        self.play(Write(ab2Texts))
        self.wait(2.0)
        self.play(self.camera.frame.animate.move_to([2,-1,2]))
        move_aaText=aaText.animate.move_to([-1,-3,-1])
        move_bbText=bbText.animate.move_to([1.5,-3,-1])
        move_ab2Texts=AnimationGroup(move_aaText,move_bbText)
        self.play(move_ab2Texts)
        plus=Text("+").scale(2.0).move_to([0.3,-3.1,-1])
        equal=Text("=").scale(2.0).move_to([2.70,-3.1,-1])
        Operators=VGroup(plus,equal)
        self.play(Write(Operators))
        self.wait(5.0)